name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every 24 hours
  workflow_dispatch:     # allows manual trigger

jobs:
  build:
    name: generate snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Tejas-Dherange
          outputs: dist/snake.svg

      - name: Push the snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
